terraform {
  required_providers {
    proxmox = {
      source  = "bpg/proxmox"
      version = "0.66.1"
    }
    talos = {
      source  = "siderolabs/talos"
      version = "~> 0.7.0"
    }
    local = {
      source  = "hashicorp/local"
      version = "~> 2.5.0"
    }
    vault = {
      source  = "hashicorp/vault"
      version = "~> 4.3.0"
    }
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "~> 2.31.0"
    }
    pihole = {
      source  = "dklesev/pihole"
      version = "~> 1.0"
    }
  }
}

provider "proxmox" {
  # These are read automatically from environment variables:
  # - PROXMOX_VE_ENDPOINT
  # - PROXMOX_VE_API_TOKEN
  # which are generated by `source bin/load-env.sh`
  insecure = true

  ssh {
    agent    = true
    username = "root"
  }
}

provider "vault" {
  address          = "https://10.7.82.90:8200"
  skip_child_token = true
  skip_tls_verify  = true
}

provider "kubernetes" {
  config_path = "${path.module}/../kubeconfig"
}

provider "pihole" {
  # Reads PIHOLE_URL and PIHOLE_PASSWORD from environment variables
}


