apiVersion: v1
kind: ConfigMap
metadata:
  name: litellm-config
  namespace: litellm
data:
  config.yaml: |
    model_list:
      - model_name: gemini-flash
        litellm_params:
          model: gemini/gemini-1.5-flash
          api_key: "os.environ/GEMINI_API_KEY"
      - model_name: gemini-pro
        litellm_params:
          model: gemini/gemini-1.5-pro
          api_key: "os.environ/GEMINI_API_KEY"
      - model_name: llama3.2
        litellm_params:
          model: ollama/llama3.2:1b
          api_base: http://ollama.ollama.svc.cluster.local:11434
    
    general_settings:
      master_key: "os.environ/LITELLM_MASTER_KEY"
      database_url: "sqlite:////data/litellm.db"
