apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prometheus-secrets
  namespace: monitoring
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: prometheus-secrets
    creationPolicy: Owner
  data:
    - secretKey: litellm-master-key
      remoteRef:
        key: secret/data/app/litellm
        property: master_key
