apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: otwld-charts
  namespace: ollama
spec:
  interval: 1h
  url: https://helm.otwld.com/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ollama
  namespace: ollama
spec:
  interval: 10m
  chart:
    spec:
      chart: ollama
      version: 1.67.0
      sourceRef:
        kind: HelmRepository
        name: otwld-charts
  values:
    ollama:
      gpu:
        enabled: false
      models:
        pull:
          - llama3.2:1b
          - qwen2.5-coder:7b
        
    persistentVolume:
      enabled: true
      storageClass: "local-path"
      size: 30Gi
      accessModes:
        - ReadWriteOnce

    resources:
      requests:
        cpu: "500m"
        memory: "2Gi"
      limits:
        cpu: "4000m"
        memory: "4Gi"

    ingress:
      enabled: true
      className: "nginx"
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      hosts:
        - host: ollama.fog.chalko.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - ollama.fog.chalko.com
          secretName: ollama-tls
