apiVersion: v1
kind: ConfigMap
metadata:
  name: dolt-config
  namespace: dolt
data:
  config.yaml: |
    listener:
      host: 0.0.0.0
      port: 3306
      tls_cert: "/etc/dolt/certs/tls.crt"
      tls_key: "/etc/dolt/certs/tls.key"
