apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dolt-secrets
  namespace: dolt
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: dolt-secrets
    creationPolicy: Owner
  data:
    - secretKey: root-password
      remoteRef:
        key: secret/data/app/dolt
        property: root_password
