apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dolt
  namespace: dolt
  labels:
    app.kubernetes.io/name: dolt
spec:
  serviceName: dolt
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: dolt
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dolt
    spec:
      containers:
        - name: dolt
          image: dolthub/dolt-sql-server:2.2.3
          imagePullPolicy: IfNotPresent
          command: ["dolt", "sql-server", "--config", "/etc/dolt/config.yaml"]
          ports:
            - containerPort: 3306
              name: mysql
          env:
            - name: DOLT_ROOT_HOST
              value: "%"
            - name: DOLT_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dolt-secrets
                  key: root-password
          volumeMounts:
            - name: dolt-data
              mountPath: /var/lib/dolt
            - name: certs-volume
              mountPath: /etc/dolt/certs
              readOnly: true
            - name: config-volume
              mountPath: /etc/dolt/config.yaml
              subPath: config.yaml
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "2000m"
              memory: "2Gi"
      volumes:
        - name: certs-volume
          secret:
            secretName: dolt-tls-secret
        - name: config-volume
          configMap:
            name: dolt-config
  volumeClaimTemplates:
    - metadata:
        name: dolt-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "local-path"
        resources:
          requests:
            storage: 10Gi
