apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oxidized-secrets
  namespace: oxidized
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: oxidized-secrets
    creationPolicy: Owner
  data:
    - secretKey: ROUTER_PASSWORD
      remoteRef:
        key: secret/data/app/oxidized
        property: router_password
