apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: netbox-secrets
  namespace: netbox
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: netbox-secrets
    creationPolicy: Owner
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: secret/data/app/netbox
        property: db_password
    - secretKey: SECRET_KEY
      remoteRef:
        key: secret/data/app/netbox
        property: secret_key
    - secretKey: SUPERUSER_PASSWORD
      remoteRef:
        key: secret/data/app/netbox
        property: superuser_password
