#!/usr/bin/env bash
# ==============================================================================
# haze - Vault Secret Retrieval Script for ComposeFlux & vLLM
# ==============================================================================
# Retrieves HF_TOKEN and stack secrets from HashiCorp Vault using AppRole auth.
# ==============================================================================

set -euo pipefail

VAULT_ADDR="${VAULT_ADDR:-https://10.7.82.90:8200}"
VAULT_SECRET_PATH="${VAULT_SECRET_PATH:-secret/data/fog/haze/vllm}"
ENV_FILE="${ENV_FILE:-/opt/composeflux/stacks/haze/.env}"
APPROLE_ROLE_ID_FILE="${APPROLE_ROLE_ID_FILE:-/etc/composeflux/vault-role-id}"
APPROLE_SECRET_ID_FILE="${APPROLE_SECRET_ID_FILE:-/etc/composeflux/vault-secret-id}"
VAULT_SKIP_VERIFY="${VAULT_SKIP_VERIFY:-true}"

log() {
  echo "[$(date -Iseconds)] [vault-sync] $*"
}

# Require curl and jq
command -v curl >/dev/null 2>&1 || { log "ERROR: curl is required"; exit 1; }
command -v jq >/dev/null 2>&1 || { log "ERROR: jq is required"; exit 1; }

# Authenticate via AppRole if role-id and secret-id files exist
VAULT_TOKEN="${VAULT_TOKEN:-}"
CURL_INSECURE_FLAG=""
if [ "$VAULT_SKIP_VERIFY" = "true" ]; then
  CURL_INSECURE_FLAG="-k"
fi

if [ -z "$VAULT_TOKEN" ]; then
  if [ -f "$APPROLE_ROLE_ID_FILE" ] && [ -f "$APPROLE_SECRET_ID_FILE" ]; then
    ROLE_ID="$(tr -d '[:space:]' < "$APPROLE_ROLE_ID_FILE")"
    SECRET_ID="$(tr -d '[:space:]' < "$APPROLE_SECRET_ID_FILE")"

    log "Authenticating with Vault AppRole at ${VAULT_ADDR}..."
    LOGIN_PAYLOAD=$(jq -n --arg r "$ROLE_ID" --arg s "$SECRET_ID" '{role_id: $r, secret_id: $s}')
    AUTH_RESP=$(curl -s $CURL_INSECURE_FLAG --fail -X POST -d "$LOGIN_PAYLOAD" "${VAULT_ADDR}/v1/auth/approle/login" || true)

    VAULT_TOKEN=$(echo "$AUTH_RESP" | jq -r '.auth.client_token // empty')
    if [ -z "$VAULT_TOKEN" ]; then
      log "WARNING: Vault AppRole authentication failed. Checking existing environment file."
      if [ -f "$ENV_FILE" ]; then
        log "Existing $ENV_FILE found. Proceeding without updating."
        exit 0
      fi
      log "ERROR: Cannot authenticate to Vault and no existing $ENV_FILE found."
      exit 1
    fi
  else
    log "NOTE: AppRole credential files not present in /etc/composeflux. Skipping Vault sync."
    exit 0
  fi
fi

log "Fetching secrets from ${VAULT_ADDR}/v1/${VAULT_SECRET_PATH}..."
SECRET_RESP=$(curl -s $CURL_INSECURE_FLAG --fail -H "X-Vault-Token: ${VAULT_TOKEN}" "${VAULT_ADDR}/v1/${VAULT_SECRET_PATH}" || true)

HF_TOKEN=$(echo "$SECRET_RESP" | jq -r '.data.data.hf_token // .data.data.HF_TOKEN // empty')

if [ -n "$HF_TOKEN" ]; then
  mkdir -p "$(dirname "$ENV_FILE")"
  umask 077
  cat <<EOF > "$ENV_FILE"
# Auto-generated by fetch-vault-secrets.sh on $(date -u)
HF_TOKEN=${HF_TOKEN}
HF_CACHE_DIR=/var/cache/huggingface
VLLM_PORT=8000
EOF
  chmod 600 "$ENV_FILE"
  log "Successfully updated $ENV_FILE with secrets from Vault."
else
  log "WARNING: No HF_TOKEN found in Vault secret payload."
fi
