apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cert-manager-dns-token
  namespace: cert-manager
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: cert-manager-dns-token
    creationPolicy: Owner
  data:
    - secretKey: service-account.json
      remoteRef:
        key: secret/data/app/cert-manager
        property: service_account_json
