apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - dns-secrets.yaml
  - cert-manager-secrets.yaml
  - cert-manager-issuers.yaml
  - gitea-secrets.yaml
  - vault-auth-setup.yaml
  - vault-store.yaml
  - external-dns.yaml
  - ingress-nginx.yaml
  - cert-manager.yaml
  - gitea.yaml
