terraform {
  required_providers {
    proxmox = {
      source  = "bpg/proxmox"
      version = "0.66.1"
    }
  }
}

provider "proxmox" {
  # These are read automatically from environment variables:
  # - PROXMOX_VE_ENDPOINT
  # - PROXMOX_VE_API_TOKEN
  # which are generated by `source bin/load-env.sh`
  insecure = true

  ssh {
    agent    = true
    username = "root"
  }
}
