apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: olah-cache-pvc
  namespace: olah
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "local-path"
  resources:
    requests:
      storage: 100Gi
