apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: harbor-charts
  namespace: harbor
spec:
  interval: 1h
  url: https://helm.goharbor.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: harbor
  namespace: harbor
spec:
  interval: 10m
  chart:
    spec:
      chart: harbor
      version: ">=1.0.0"
      sourceRef:

        kind: HelmRepository
        name: harbor-charts
  values:
    existingSecretAdminPassword: "harbor-secret"
    existingSecretSecretKey: "harbor-secret"
    expose:
      type: ingress
      tls:
        enabled: true
        certSource: secret
        secret:
          secretName: harbor-tls
      ingress:
        hosts:
          core: harbor.fog.chalko.com
        className: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
          nginx.ingress.kubernetes.io/proxy-body-size: "0"
          nginx.ingress.kubernetes.io/proxy-read-timeout: "900"
          nginx.ingress.kubernetes.io/proxy-send-timeout: "900"
          ingress.kubernetes.io/ssl-redirect: "true"
    externalURL: https://harbor.fog.chalko.com


    persistence:
      persistentVolumeClaim:
        registry:
          storageClass: local-path
          size: 50Gi
        chartmuseum:
          storageClass: local-path
          size: 5Gi
        jobservice:
          jobLog:
            storageClass: local-path
            size: 5Gi
        database:
          storageClass: local-path
          size: 5Gi
        redis:
          storageClass: local-path
          size: 5Gi
        trivy:
          storageClass: local-path
          size: 5Gi
