apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-secret
  namespace: harbor
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: harbor-secret
    creationPolicy: Owner
  data:
    - secretKey: secret
      remoteRef:
        key: secret/data/app/harbor
        property: secret_key
    - secretKey: HARBOR_ADMIN_PASSWORD
      remoteRef:
        key: secret/data/app/harbor
        property: admin_password
