apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: librenms-secrets
  namespace: librenms
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: librenms-secrets
    creationPolicy: Owner
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: secret/data/app/librenms
        property: db_password
    - secretKey: DB_ROOT_PASSWORD
      remoteRef:
        key: secret/data/app/librenms
        property: db_root_password
