apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-tls
  namespace: monitoring
spec:
  secretName: grafana-tls
  dnsNames:
    - grafana.fog.chalko.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
